// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: order/api/client/notificationinternal/notificationinternal.proto

package notificationinternal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_order_api_client_notificationinternal_notificationinternal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_api_client_notificationinternal_notificationinternal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_order_api_client_notificationinternal_notificationinternal_proto_rawDescGZIP(), []int{0}
}

func (x *SendNotificationRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *SendNotificationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_order_api_client_notificationinternal_notificationinternal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_api_client_notificationinternal_notificationinternal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_order_api_client_notificationinternal_notificationinternal_proto_rawDescGZIP(), []int{1}
}

func (x *SendNotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_order_api_client_notificationinternal_notificationinternal_proto protoreflect.FileDescriptor

const file_order_api_client_notificationinternal_notificationinternal_proto_rawDesc = "" +
	"\n" +
	"@order/api/client/notificationinternal/notificationinternal.proto\x12\fNotification\"K\n" +
	"\x17SendNotificationRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x18SendNotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x80\x01\n" +
	"\x1bNotificationInternalService\x12a\n" +
	"\x10SendNotification\x12%.Notification.SendNotificationRequest\x1a&.Notification.SendNotificationResponseB\x19Z\x17/.;notificationinternalb\x06proto3"

var (
	file_order_api_client_notificationinternal_notificationinternal_proto_rawDescOnce sync.Once
	file_order_api_client_notificationinternal_notificationinternal_proto_rawDescData []byte
)

func file_order_api_client_notificationinternal_notificationinternal_proto_rawDescGZIP() []byte {
	file_order_api_client_notificationinternal_notificationinternal_proto_rawDescOnce.Do(func() {
		file_order_api_client_notificationinternal_notificationinternal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_api_client_notificationinternal_notificationinternal_proto_rawDesc), len(file_order_api_client_notificationinternal_notificationinternal_proto_rawDesc)))
	})
	return file_order_api_client_notificationinternal_notificationinternal_proto_rawDescData
}

var file_order_api_client_notificationinternal_notificationinternal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_order_api_client_notificationinternal_notificationinternal_proto_goTypes = []any{
	(*SendNotificationRequest)(nil),  // 0: Notification.SendNotificationRequest
	(*SendNotificationResponse)(nil), // 1: Notification.SendNotificationResponse
}
var file_order_api_client_notificationinternal_notificationinternal_proto_depIdxs = []int32{
	0, // 0: Notification.NotificationInternalService.SendNotification:input_type -> Notification.SendNotificationRequest
	1, // 1: Notification.NotificationInternalService.SendNotification:output_type -> Notification.SendNotificationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_api_client_notificationinternal_notificationinternal_proto_init() }
func file_order_api_client_notificationinternal_notificationinternal_proto_init() {
	if File_order_api_client_notificationinternal_notificationinternal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_api_client_notificationinternal_notificationinternal_proto_rawDesc), len(file_order_api_client_notificationinternal_notificationinternal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_api_client_notificationinternal_notificationinternal_proto_goTypes,
		DependencyIndexes: file_order_api_client_notificationinternal_notificationinternal_proto_depIdxs,
		MessageInfos:      file_order_api_client_notificationinternal_notificationinternal_proto_msgTypes,
	}.Build()
	File_order_api_client_notificationinternal_notificationinternal_proto = out.File
	file_order_api_client_notificationinternal_notificationinternal_proto_goTypes = nil
	file_order_api_client_notificationinternal_notificationinternal_proto_depIdxs = nil
}
