// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: order/api/client/notificationinternal/notificationinternal.proto

package notificationinternal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificationInternalService_SendNotification_FullMethodName = "/Notification.NotificationInternalService/SendNotification"
)

// NotificationInternalServiceClient is the client API for NotificationInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationInternalServiceClient interface {
	SendNotification(ctx context.Context, in *SendNotificationRequest, opts ...grpc.CallOption) (*SendNotificationResponse, error)
}

type notificationInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationInternalServiceClient(cc grpc.ClientConnInterface) NotificationInternalServiceClient {
	return &notificationInternalServiceClient{cc}
}

func (c *notificationInternalServiceClient) SendNotification(ctx context.Context, in *SendNotificationRequest, opts ...grpc.CallOption) (*SendNotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendNotificationResponse)
	err := c.cc.Invoke(ctx, NotificationInternalService_SendNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationInternalServiceServer is the server API for NotificationInternalService service.
// All implementations must embed UnimplementedNotificationInternalServiceServer
// for forward compatibility.
type NotificationInternalServiceServer interface {
	SendNotification(context.Context, *SendNotificationRequest) (*SendNotificationResponse, error)
	mustEmbedUnimplementedNotificationInternalServiceServer()
}

// UnimplementedNotificationInternalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationInternalServiceServer struct{}

func (UnimplementedNotificationInternalServiceServer) SendNotification(context.Context, *SendNotificationRequest) (*SendNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendNotification not implemented")
}
func (UnimplementedNotificationInternalServiceServer) mustEmbedUnimplementedNotificationInternalServiceServer() {
}
func (UnimplementedNotificationInternalServiceServer) testEmbeddedByValue() {}

// UnsafeNotificationInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationInternalServiceServer will
// result in compilation errors.
type UnsafeNotificationInternalServiceServer interface {
	mustEmbedUnimplementedNotificationInternalServiceServer()
}

func RegisterNotificationInternalServiceServer(s grpc.ServiceRegistrar, srv NotificationInternalServiceServer) {
	// If the following call pancis, it indicates UnimplementedNotificationInternalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationInternalService_ServiceDesc, srv)
}

func _NotificationInternalService_SendNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationInternalServiceServer).SendNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationInternalService_SendNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationInternalServiceServer).SendNotification(ctx, req.(*SendNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationInternalService_ServiceDesc is the grpc.ServiceDesc for NotificationInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Notification.NotificationInternalService",
	HandlerType: (*NotificationInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendNotification",
			Handler:    _NotificationInternalService_SendNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order/api/client/notificationinternal/notificationinternal.proto",
}
