// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: order/api/client/paymentserviceinternal/paymentserviceinternal.proto

package paymentserviceinternal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_rawDescGZIP(), []int{0}
}

func (x *GetBalanceRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       float64                `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_rawDescGZIP(), []int{1}
}

func (x *GetBalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type ProcessPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderID       string                 `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	UserID        string                 `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentRequest) Reset() {
	*x = ProcessPaymentRequest{}
	mi := &file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRequest) ProtoMessage() {}

func (x *ProcessPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessPaymentRequest) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *ProcessPaymentRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *ProcessPaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ProcessPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TransactionID string                 `protobuf:"bytes,2,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentResponse) Reset() {
	*x = ProcessPaymentResponse{}
	mi := &file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentResponse) ProtoMessage() {}

func (x *ProcessPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentResponse.ProtoReflect.Descriptor instead.
func (*ProcessPaymentResponse) Descriptor() ([]byte, []int) {
	return file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessPaymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessPaymentResponse) GetTransactionID() string {
	if x != nil {
		return x.TransactionID
	}
	return ""
}

var File_order_api_client_paymentserviceinternal_paymentserviceinternal_proto protoreflect.FileDescriptor

const file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_rawDesc = "" +
	"\n" +
	"Dorder/api/client/paymentserviceinternal/paymentserviceinternal.proto\x12\aPayment\"+\n" +
	"\x11GetBalanceRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\".\n" +
	"\x12GetBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x01R\abalance\"a\n" +
	"\x15ProcessPaymentRequest\x12\x18\n" +
	"\aorderID\x18\x01 \x01(\tR\aorderID\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\tR\x06userID\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"X\n" +
	"\x16ProcessPaymentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12$\n" +
	"\rtransactionID\x18\x02 \x01(\tR\rtransactionID2\xb2\x01\n" +
	"\x16PaymentServiceInternal\x12E\n" +
	"\n" +
	"GetBalance\x12\x1a.Payment.GetBalanceRequest\x1a\x1b.Payment.GetBalanceResponse\x12Q\n" +
	"\x0eProcessPayment\x12\x1e.Payment.ProcessPaymentRequest\x1a\x1f.Payment.ProcessPaymentResponseB\x1bZ\x19/.;paymentserviceinternalb\x06proto3"

var (
	file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_rawDescOnce sync.Once
	file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_rawDescData []byte
)

func file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_rawDescGZIP() []byte {
	file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_rawDescOnce.Do(func() {
		file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_rawDesc), len(file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_rawDesc)))
	})
	return file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_rawDescData
}

var file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_goTypes = []any{
	(*GetBalanceRequest)(nil),      // 0: Payment.GetBalanceRequest
	(*GetBalanceResponse)(nil),     // 1: Payment.GetBalanceResponse
	(*ProcessPaymentRequest)(nil),  // 2: Payment.ProcessPaymentRequest
	(*ProcessPaymentResponse)(nil), // 3: Payment.ProcessPaymentResponse
}
var file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_depIdxs = []int32{
	0, // 0: Payment.PaymentServiceInternal.GetBalance:input_type -> Payment.GetBalanceRequest
	2, // 1: Payment.PaymentServiceInternal.ProcessPayment:input_type -> Payment.ProcessPaymentRequest
	1, // 2: Payment.PaymentServiceInternal.GetBalance:output_type -> Payment.GetBalanceResponse
	3, // 3: Payment.PaymentServiceInternal.ProcessPayment:output_type -> Payment.ProcessPaymentResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_init() }
func file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_init() {
	if File_order_api_client_paymentserviceinternal_paymentserviceinternal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_rawDesc), len(file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_goTypes,
		DependencyIndexes: file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_depIdxs,
		MessageInfos:      file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_msgTypes,
	}.Build()
	File_order_api_client_paymentserviceinternal_paymentserviceinternal_proto = out.File
	file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_goTypes = nil
	file_order_api_client_paymentserviceinternal_paymentserviceinternal_proto_depIdxs = nil
}
