// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: order/api/client/productinternal/productinternal.proto

package productinternal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreProductRequest) Reset() {
	*x = StoreProductRequest{}
	mi := &file_order_api_client_productinternal_productinternal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreProductRequest) ProtoMessage() {}

func (x *StoreProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_api_client_productinternal_productinternal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreProductRequest.ProtoReflect.Descriptor instead.
func (*StoreProductRequest) Descriptor() ([]byte, []int) {
	return file_order_api_client_productinternal_productinternal_proto_rawDescGZIP(), []int{0}
}

func (x *StoreProductRequest) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type StoreProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     string                 `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreProductResponse) Reset() {
	*x = StoreProductResponse{}
	mi := &file_order_api_client_productinternal_productinternal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreProductResponse) ProtoMessage() {}

func (x *StoreProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_api_client_productinternal_productinternal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreProductResponse.ProtoReflect.Descriptor instead.
func (*StoreProductResponse) Descriptor() ([]byte, []int) {
	return file_order_api_client_productinternal_productinternal_proto_rawDescGZIP(), []int{1}
}

func (x *StoreProductResponse) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

type FindProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     string                 `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindProductRequest) Reset() {
	*x = FindProductRequest{}
	mi := &file_order_api_client_productinternal_productinternal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindProductRequest) ProtoMessage() {}

func (x *FindProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_api_client_productinternal_productinternal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindProductRequest.ProtoReflect.Descriptor instead.
func (*FindProductRequest) Descriptor() ([]byte, []int) {
	return file_order_api_client_productinternal_productinternal_proto_rawDescGZIP(), []int{2}
}

func (x *FindProductRequest) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

type FindProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3,oneof" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindProductResponse) Reset() {
	*x = FindProductResponse{}
	mi := &file_order_api_client_productinternal_productinternal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindProductResponse) ProtoMessage() {}

func (x *FindProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_api_client_productinternal_productinternal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindProductResponse.ProtoReflect.Descriptor instead.
func (*FindProductResponse) Descriptor() ([]byte, []int) {
	return file_order_api_client_productinternal_productinternal_proto_rawDescGZIP(), []int{3}
}

func (x *FindProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_order_api_client_productinternal_productinternal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_api_client_productinternal_productinternal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_order_api_client_productinternal_productinternal_proto_rawDescGZIP(), []int{4}
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_order_api_client_productinternal_productinternal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_api_client_productinternal_productinternal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_order_api_client_productinternal_productinternal_proto_rawDescGZIP(), []int{5}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     string                 `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_order_api_client_productinternal_productinternal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_order_api_client_productinternal_productinternal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_order_api_client_productinternal_productinternal_proto_rawDescGZIP(), []int{6}
}

func (x *Product) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_order_api_client_productinternal_productinternal_proto protoreflect.FileDescriptor

const file_order_api_client_productinternal_productinternal_proto_rawDesc = "" +
	"\n" +
	"6order/api/client/productinternal/productinternal.proto\x12\aProduct\"A\n" +
	"\x13StoreProductRequest\x12*\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.Product.ProductR\aproduct\"4\n" +
	"\x14StoreProductResponse\x12\x1c\n" +
	"\tproductID\x18\x01 \x01(\tR\tproductID\"2\n" +
	"\x12FindProductRequest\x12\x1c\n" +
	"\tproductID\x18\x01 \x01(\tR\tproductID\"R\n" +
	"\x13FindProductResponse\x12/\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.Product.ProductH\x00R\aproduct\x88\x01\x01B\n" +
	"\n" +
	"\b_product\"\x15\n" +
	"\x13ListProductsRequest\"D\n" +
	"\x14ListProductsResponse\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.Product.ProductR\bproducts\"s\n" +
	"\aProduct\x12\x1c\n" +
	"\tproductID\x18\x01 \x01(\tR\tproductID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price2\xfc\x01\n" +
	"\x16ProductInternalService\x12K\n" +
	"\fStoreProduct\x12\x1c.Product.StoreProductRequest\x1a\x1d.Product.StoreProductResponse\x12H\n" +
	"\vFindProduct\x12\x1b.Product.FindProductRequest\x1a\x1c.Product.FindProductResponse\x12K\n" +
	"\fListProducts\x12\x1c.Product.ListProductsRequest\x1a\x1d.Product.ListProductsResponseB\x14Z\x12/.;productinternalb\x06proto3"

var (
	file_order_api_client_productinternal_productinternal_proto_rawDescOnce sync.Once
	file_order_api_client_productinternal_productinternal_proto_rawDescData []byte
)

func file_order_api_client_productinternal_productinternal_proto_rawDescGZIP() []byte {
	file_order_api_client_productinternal_productinternal_proto_rawDescOnce.Do(func() {
		file_order_api_client_productinternal_productinternal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_api_client_productinternal_productinternal_proto_rawDesc), len(file_order_api_client_productinternal_productinternal_proto_rawDesc)))
	})
	return file_order_api_client_productinternal_productinternal_proto_rawDescData
}

var file_order_api_client_productinternal_productinternal_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_order_api_client_productinternal_productinternal_proto_goTypes = []any{
	(*StoreProductRequest)(nil),  // 0: Product.StoreProductRequest
	(*StoreProductResponse)(nil), // 1: Product.StoreProductResponse
	(*FindProductRequest)(nil),   // 2: Product.FindProductRequest
	(*FindProductResponse)(nil),  // 3: Product.FindProductResponse
	(*ListProductsRequest)(nil),  // 4: Product.ListProductsRequest
	(*ListProductsResponse)(nil), // 5: Product.ListProductsResponse
	(*Product)(nil),              // 6: Product.Product
}
var file_order_api_client_productinternal_productinternal_proto_depIdxs = []int32{
	6, // 0: Product.StoreProductRequest.product:type_name -> Product.Product
	6, // 1: Product.FindProductResponse.product:type_name -> Product.Product
	6, // 2: Product.ListProductsResponse.products:type_name -> Product.Product
	0, // 3: Product.ProductInternalService.StoreProduct:input_type -> Product.StoreProductRequest
	2, // 4: Product.ProductInternalService.FindProduct:input_type -> Product.FindProductRequest
	4, // 5: Product.ProductInternalService.ListProducts:input_type -> Product.ListProductsRequest
	1, // 6: Product.ProductInternalService.StoreProduct:output_type -> Product.StoreProductResponse
	3, // 7: Product.ProductInternalService.FindProduct:output_type -> Product.FindProductResponse
	5, // 8: Product.ProductInternalService.ListProducts:output_type -> Product.ListProductsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_order_api_client_productinternal_productinternal_proto_init() }
func file_order_api_client_productinternal_productinternal_proto_init() {
	if File_order_api_client_productinternal_productinternal_proto != nil {
		return
	}
	file_order_api_client_productinternal_productinternal_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_api_client_productinternal_productinternal_proto_rawDesc), len(file_order_api_client_productinternal_productinternal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_api_client_productinternal_productinternal_proto_goTypes,
		DependencyIndexes: file_order_api_client_productinternal_productinternal_proto_depIdxs,
		MessageInfos:      file_order_api_client_productinternal_productinternal_proto_msgTypes,
	}.Build()
	File_order_api_client_productinternal_productinternal_proto = out.File
	file_order_api_client_productinternal_productinternal_proto_goTypes = nil
	file_order_api_client_productinternal_productinternal_proto_depIdxs = nil
}
